apiVersion: apps/v1
kind: Deployment
metadata:
  name: proclone-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proclone-backend
  template:
    metadata:
      labels:
        app: proclone-backend
    spec:
      containers:
        - name: proclone-backend
          image: ghcr.io/cpp-cyber/proclone:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: uploads
              mountPath: /app/uploads
          env:
            - name: REDIS_ADDR
              value: "redis-master.default.svc.cluster.local:6379"
            - name: REDIS_PASSWORD
              value: ""
            - name: STORAGE_ID
              value: "[your shared storage ID]"
          envFrom:
            - secretRef:
                name: proclone-secrets
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: proclone-backend-pvc
