apiVersion: apps/v1
kind: Deployment
metadata:
  name: pc-front
  labels:
    app: pc-front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pc-front
  template:
    metadata:
      labels:
        app: pc-front
    spec:
      containers:
        - name: pc-front
          image: ghcr.io/cpp-cyber/faculty-kamino-frontend:latest
          ports:
            - containerPort: 80
